command.generic.must_be_player=<theme:error>You must be a player to execute this command.
command.timetrial.unknown_track=<theme:error>Unknown track '<arg:0>'.
message.openboatutils.outdated_version_global=<theme:error>Warning! Your version of OpenBoatUtils is too old for this server. Please update for it to function.
message.openboatutils.bad_version=<theme:error>Warning! Your version of OpenBoatUtils is broken (<arg:0>) and will not be used. Please update for it to function.
message.openboatutils.failed_transaction=<theme:error>OpenBoatUtils failed to respond to a transaction.
message.openboatutils.warning_unstable=<theme:error>Warning! You are on an unstable build of OpenBoatUtils.
message.timetrial.start=<theme:main>Started a timetrial at <track>.
message.timetrial.requires_open_boat_utils=<theme:error>This track required OpenBoatUtils.
message.race.no_grid_with_index=<theme:error>No grid with that index.