command.generic.must_be_player=<theme:error>You must be a player to execute this command.
command.generic.unknown_track=<theme:error>Unknown track '<theme:special><arg:0></theme:special>'.
command.generic.failed_to_load_track=<theme:error>Failed to load '<theme:special><arg:0></theme:special>'.
command.generic.loading_track=<theme:main>Loading '<theme:special><arg:0></theme:special>'.
command.reset.not_timetrialing=<theme:error>You aren't time trialing.
command.boat.not_on_ground=<theme:error>You must be on the ground.
command.boat.not_here=<theme:error>You can't spawn a boat here.
command.boat.already_in_boat=<theme:error>You're already in a boat.
command.event.load.failed_to_load_file=<theme:error>Failed to open <filename>. See logs for more details.
command.event.load.failed_to_compile_file=<theme:error>Failed to compile <filename>. See logs for more details.
command.event.load.failed_to_find_event=<theme:error>Failed to find <filename>.
command.event.load.compiled_in=<theme:main>Compiled <filename> in <theme:special><time>ms</theme:special>.
command.event.stage.no_loaded_stages=<theme:error>No loaded stages for event <theme:special><event></theme:special>.
command.event.stage.list_stages=<theme:main>Stages for event <theme:special><event></theme:special>: <theme:special><stages></theme:special>
command.event.stage.not_stateful=<theme:error>Stage <theme:special><stage></theme:special> does not have a state.
command.event.stage.info=<theme:main>Stage <theme:special><stage></theme:special> (Event: <event>) is in state <theme:special><state></theme:special>. Available transitions: <theme:special><transitions></theme:special>
command.event.stage.invalid_transition=<theme:error>Invalid transition '<theme:special><transition></theme:special>' for stage <stage>.
command.event.stage.transitioned=<theme:main>Executed transition '<theme:special><transition></theme:special>' on stage <theme:special><stage></theme:special>.
command.event.stage.not_found=<theme:error>Failed to find stage '<theme:special><stage></theme:special>'.
command.event.state.not_found=<theme:error>Failed to find active event '<theme:special><event></theme:special>'.
message.openboatutils.outdated_version_global=<theme:error>Warning! Your version of OpenBoatUtils is too old for this server. Please update for it to function.
message.openboatutils.bad_version=<theme:error>Warning! Your version of OpenBoatUtils is broken (<theme:special><arg:0></theme:special>). Please update for it to function.
message.openboatutils.failed_transaction=<theme:error>OpenBoatUtils failed to respond to a transaction.
message.openboatutils.warning_unstable=<theme:error>Warning! You are on an unstable build of OpenBoatUtils.
message.openboatutils.block_unstable=<theme:error>Error! You are on an unstable build of OpenBoatUtils. Please update to the latest stable version.
message.timetrial.start=<theme:main>Started a timetrial at <theme:special><track><theme:special>.
message.timetrial.requires_open_boat_utils=<theme:error>This track requires OpenBoatUtils.
message.timetrial.checkpoint_pass=<theme:main>Checkpoint <theme:special><checkpoint></theme:special> >> <time> <delta>
message.timetrial.checkpoint_pass_no_delta=<theme:main>Checkpoint <theme:special><checkpoint></theme:special> >> <time>
message.timetrial.practicepoint_place=<theme:main>Practice point <theme:special>placed</theme:special>
message.timetrial.practicepoint_remove=<theme:main>Practice point <theme:special>removed</theme:special>
message.lap.complete_checkpoint_first=<theme:main>Completed <theme:special><checkpoints>C</theme:special> of <track> in <time>
message.lap.complete_checkpoint=<theme:main>Completed <theme:special><checkpoints>C</theme:special> of <track> in <time> <delta>
message.lap.complete_first=<theme:main>Completed <track> in <theme:special><time></theme:special>
message.lap.complete=<theme:main>Completed <track> in <theme:special><time></theme:special> <delta>
message.race.completed=<theme:main>Finished <theme:special><laps></theme:special> laps on <track> in <theme:special><time></theme:special>
message.race.error.failed_to_grid=<theme:error>Failed to teleport you to your grid location.