command.generic.must_be_player=<theme:error>You must be a player to execute this command.
command.generic.unknown_track=<theme:error>Unknown track '<theme:special><arg:0></theme:special>'.
command.generic.failed_to_load_track=<theme:error>Failed to load '<theme:special><arg:0></theme:special>'.
command.generic.loading_track=<theme:main>Loading '<theme:special><arg:0></theme:special>'.
command.reset.not_timetrialing=<theme:error>You aren't time trialing.
command.boat.not_on_ground=<theme:error>You must be on the ground.
command.boat.not_here=<theme:error>You can't spawn a boat here.
command.boat.already_in_boat=<theme:error>You're already in a boat.
message.openboatutils.outdated_version_global=<theme:error>Warning! Your version of OpenBoatUtils is too old for this server. Please update for it to function.
message.openboatutils.bad_version=<theme:error>Warning! Your version of OpenBoatUtils is broken (<theme:special><arg:0></theme:special>). Please update for it to function.
message.openboatutils.failed_transaction=<theme:error>OpenBoatUtils failed to respond to a transaction.
message.openboatutils.warning_unstable=<theme:error>Warning! You are on an unstable build of OpenBoatUtils.
message.openboatutils.block_unstable=<theme:error>Error! You are on an unstable build of OpenBoatUtils. Please update to the latest stable version.
message.timetrial.start=<theme:main>Started a timetrial at <theme:special><track><theme:special>.
message.timetrial.requires_open_boat_utils=<theme:error>This track requires OpenBoatUtils.
message.timetrial.complete_checkpoint_first=<theme:main>Completed <theme:special><checkpoints>C</theme:special> of <track> in <time>
message.timetrial.complete_checkpoint=<theme:main>Completed <theme:special><checkpoints>C</theme:special> of <track> in <time> <delta>
message.timetrial.complete_first=<theme:main>Completed <track> in <time>
message.timetrial.complete=<theme:main>Completed <track> in <time> <delta>
message.timetrail.checkpoint_pass=<theme:main>Checkpoint <theme:special><checkpoint></theme:special> | <time> <delta>
message.timetrail.checkpoint_pass_no_delta=<theme:main>Checkpoint <theme:special><checkpoint></theme:special> | <time>