package io.gitlab.icestom.icestom.web;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import org.jetbrains.annotations.Nullable;

import java.util.Map;

final class LuauWriter {

    private static final String MARKER = "-- @panel ";

    private LuauWriter() {}

    static String write(EventDocument document) {
        StringBuilder out = new StringBuilder();

        out.append("-- Generated by the IceStom panel.\n");
        out.append("-- The marker comment below is how the panel reopens this event in the builder.\n");
        out.append("-- Editing this file by hand is fine, but saving from the builder overwrites it.\n");
        out.append(MARKER).append(Http.GSON.toJson(document.toJson())).append('\n');
        out.append('\n');
        out.append("local manifest = {\n");
        out.append("    name = ").append(quote(document.name())).append(",\n");
        out.append("}\n");
        out.append('\n');
        out.append("local function run(event, results)\n");

        for (EventDocument.Stage stage : document.stages()) {
            out.append("    do\n");
            out.append("        local stage = event:makeStage(").append(quote(stage.type())).append(", {\n");
            out.append("            name = ").append(quote(stage.name())).append(",\n");

            for (Map.Entry<String, Object> option : stage.options().entrySet()) {
                if (option.getKey().equals("name")) continue;

                out.append("            ")
                        .append(option.getKey())
                        .append(" = ")
                        .append(value(option.getValue()))
                        .append(",\n");
            }

            out.append("        })\n");
            out.append('\n');
            out.append("        results = stage:begin(results):join()\n");
            out.append("    end\n");
            out.append('\n');
        }

        out.append("    return results\n");
        out.append("end\n");
        out.append('\n');
        out.append("return manifest, run\n");

        return out.toString();
    }

    static @Nullable EventDocument read(String source) {
        for (String line : source.split("\r?\n")) {
            String trimmed = line.trim();

            if (!trimmed.startsWith(MARKER)) continue;

            try {
                JsonElement parsed = JsonParser.parseString(trimmed.substring(MARKER.length()));

                if (!parsed.isJsonObject()) return null;

                return EventDocument.fromJson(parsed.getAsJsonObject());
            } catch (RuntimeException e) {
                return null;
            }
        }

        return null;
    }

    private static String value(Object value) {
        if (value instanceof Boolean bool) return bool.toString();

        if (value instanceof Number number) {
            double d = number.doubleValue();

            if (d == Math.rint(d) && !Double.isInfinite(d)) return Long.toString((long) d);

            return Double.toString(d);
        }

        return quote(String.valueOf(value));
    }

    private static String quote(String value) {
        StringBuilder out = new StringBuilder(value.length() + 2);
        out.append('"');

        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);

            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 0x20 || c == 0x7f) {
                        out.append(String.format("\\%03d", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }

        return out.append('"').toString();
    }
}
